[package]
name = "merkle-champ-pack"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Indexed immutable packs of merkle-champ node preimages"

[dependencies]
merkle-champ = { git = "https://github.com/tabcomputing/merkle-champ", rev = "37d2dcd48a32e4c6961f634b660b90cf2c8bc3f4" }
sha2 = "0.10.9"
